### ISSUE TITLE
Possible improvement

### ISSUE THREAD

**Issue by dwf2008** [aleixsr/Ryzentosh#12]
Your readme is very helpful in that it lists the kexts and other files needed. To make it even better, add a second column and describe why the file is  needed. Is it a hardware requirement? If so, which piece of hardware is it related to? That way, if my build is slightly different I would know that I need to look for a different file to replace the one you listed. 

Most of the descriptions and tutorials on how to build a hackintosh run and read like they are for someone who has done this a dozen times before. For a beginner they usually become very confusing very fast. So anything that will simplify the process will be very appreciated.

Thanks

**Comment by aleixsr** [comment]
Done.
You can now Buy me a Coffee ;)
