### ISSUE TITLE
No issue with DP audio after applying `Shaneee - mtrr_update_action - fix PAT`

### ISSUE THREAD

**Issue by W-KE** [aleixsr/Ryzentosh#4]
Got around 25fps with `algrey - mtrr_update_action - fix PAT` and around 300fps with `Shaneee - mtrr_update_action - fix PAT` in Minecraft.

`Shaneee - mtrr_update_action - fix PAT [my default] : Full FPS on gaming but issues using HDMI/DP audio.`
But I haven't got any audio issue with DP.

Component | Model
-- | --
CPU | AMD Ryzen 9 3900X
RAM | 64GB (2 x 32GB) DDR4 @2666MHz CL16
Mobo | ROG Strix X570-E Gaming
Graphics | GIGABYTE Radeon™ RX 5700 XT 8G Reference
OC | 0.6.3

**Comment by aleixsr** [comment]
Hello,
bug confirmed again, sound crackling using two different monitors.
