### ISSUE TITLE
No audio with HDMI or DP(Fixed)

### ISSUE THREAD

**Issue by evenlee** [aleixsr/Ryzentosh#5]
I've used previous efi and 5500xt，and tried many means but still cannot get audio on my monitors by either HDMI or DP, but when I saw the v21.09.16, I give it a go, then the magic works, I can have audio from my monitor now, this version is awesome!!! I create this issue just let people who may have same issue with me to know it, thanks again for the efi update.

**Comment by evenlee** [comment]
close as it is fixed in v21.09.16

**Comment by aleixsr** [comment]
Thanks!
