### ISSUE TITLE
Any plan to upgrade to monterey?

### ISSUE THREAD

**Issue by evenlee** [aleixsr/Ryzentosh#6]
Hi @aleixsr 

Monterey has been released for a while, do you have a plan to upgrade?

**Comment by aleixsr** [comment]
Yes of course I will, when apple fixes current super buggy release of Monterrey 😉

**Comment by evenlee** [comment]
Super, thanks.

**Comment by evenlee** [comment]
[config.plist.zip](https://github.com/aleixsr/Ryzentosh/files/7921923/config.plist.zip)
I've updated to monterey by using the config, everything is fine except bluetooth, it cannot work after sleep, someone said it should be the reason that bluetooth card has not been build as internal, i used the usbprots.kext in your EFI, i suposed it should be mapped correctly, right?
