### ISSUE TITLE
Question: what's MHz of RAM on about Page

### ISSUE THREAD

**Issue by evenlee** [aleixsr/Ryzentosh#8]
Hi @aleixsr 

I've made a build based on your config,  and I also opened the xmp in bios, but looks like the about page in Mac only show 2133 MHz, can you help to confirm your build, thanks in advance.

FYI: I have 2 DDR4 @3600MHz RAM, and the Bios do show them as 3600.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/4009476/201481277-24620058-bb17-4729-b24e-53fd2b4529d1.png">

**Comment by aleixsr** [comment]
In my case it is ok:
![image](https://user-images.githubusercontent.com/11422299/201525360-25f20903-d157-44ac-8410-665422452cc3.png)

**Comment by evenlee** [comment]
Thanks you, seems yours are right, any idea on the wrong MHz of my build?

**Comment by aleixsr** [comment]
Can you try to change RAM speed to 3200 Mhz just to test ?

**Comment by evenlee** [comment]
not sure how to set,  can you hint?
I double checked bios setting, seems the MHz is wrong even I've opened xmp.
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/4009476/201526848-7467821c-9c45-4dbf-96b2-62b37e66039d.png">

**Comment by evenlee** [comment]
may be a bios bug or something, thanks for the help
